# Model Params
## Hyperparams
hidden_size: 1024
num_epochs: 100
learning_rate: 0.1
batch_size: 64
topk: 5 
boundary_smoothing: 9 #smooth over 10 features
## others
force_cpu: false
log_interval: 100
update_dataloader: True
dataloader_cache_path: /scratch/shantanuagar_umass_edu/ego4d/nlq/


# Video Preprocessing Parameters
input_train_split: data/annotations/sample/sample_nlq_train.json
input_val_split: data/annotations/sample/sample_nlq_val.json
input_test_split: data/annotations/sample/sample_nlq_test.json
video_feature_read_path: data/video_features/
clip_feature_save_path: data/saved_clip_features/ # save path for output clip features
output_save_path: data/nlq_official_v1 # save path for clip info along with train-val split
#dataset config
dataset_config_path: ./dataset_config.yaml